language: php

php:
  - "5.4"
  - "5.5"

env:
  - SYMFONY_VERSION="2.1.*"
  - SYMFONY_VERSION="2.2.*"
  - SYMFONY_VERSION="2.3.*"
  - SYMFONY_VERSION="dev-master"

before_script:
  - pecl install gearman
  - composer require symfony/framework-bundle:${SYMFONY_VERSION}

script: phpunit --configuration phpunit.xml.dist

notifications:
  email: "build@litgroup.ru"
